MNI_mask: /Users/jeff/gDrive/jeffCloud/real-time/b2b/data/juelich_prob_GMPrimaryMotorCortexBA4p_L_50prob.nii.gz
MNI_standard: /Users/jeff/gDrive/jeffCloud/real-time/pyneal/utils/MNI_templates/MNI152_T1_1mm_brain.nii.gz
createFuncBrainMask: false
outputPrefix: test
skullStrip: true
subjAnat: /Users/jeff/gDrive/jeffCloud/real-time/b2b/pilotScans/pilot2_offline/pilot2_anat_MPRAGE.nii.gz
subjFunc: /Users/jeff/gDrive/jeffCloud/real-time/b2b/pilotScans/pilot2_offline/func_0003.nii.gz
transformMaskToFunc: true
