MNI_mask: /Users/jeff/gDrive/jeffCloud/real-time/b2b/data/juelich_prob_GMPrimaryMotorCortexBA4p_L_50prob.nii.gz
MNI_standard: /Users/jeff/gDrive/jeffCloud/real-time/pyneal/utils/MNI_templates/MNI152_T1_1mm_brain.nii.gz
createFuncBrainMask: true
outputPrefix: motorCortex_50prob
skullStrip: true
subjAnat: /Users/jeff/gDrive/jeffCloud/real-time/b2b/data/subject001/anat_brain.nii.gz
subjFunc: /Users/jeff/gDrive/jeffCloud/real-time/b2b/data/subject001/pyneal_005/exampleFunc.nii.gz
transformMaskToFunc: true
