analysisChoice: Average
dashboardClientPort: 5558
dashboardPort: 5557
launchDashboard: true
maskFile: /Users/jeff/gDrive/jeffCloud/real-time/b2b/dummyMask_80-80-30.nii.gz
maskIsWeighted: false
numTimepts: 93
outputPath: /Users/jeff/Desktop/development/pynealOutput
pynealHost: 127.0.0.1
pynealScannerPort: 5555
resultsServerPort: 5556
