analysisChoice: Average
dashboardClientPort: 5558
dashboardPort: 5557
launchDashboard: true
maskFile: /Users/jeff/gDrive/jeffCloud/real-time/b2b/data/subject001/pyneal_002/mask_transforms/FUNC_masks/motorSphere_5mm_FUNC_mask.nii.gz
maskIsWeighted: false
numTimepts: 186
outputPath: /Users/jeff/Desktop/development/pynealOutput
pynealHost: 127.0.0.1
pynealScannerPort: 5555
resultsServerPort: 5556
