analysisChoice: Average
dashboardClientPort: 5558
dashboardPort: 5557
launchDashboard: true
maskFile: /Users/jeff/gDrive/jeffCloud/real-time/pyneal/pyneal_scanner/data/Philips_0004_mask.nii.gz
maskIsWeighted: false
numTimepts: 60
outputPath: /Users/jeff/Desktop/development/pynealOutput
pynealScannerPort: 5555
resultsServerPort: 5556
