analysisChoice: Average
dashboardClientPort: 5558
dashboardPort: 5557
launchDashboard: true
maskFile: /Users/jeff/gDrive/jeffCloud/real-time/pyneal/sandbox/testMask_64-64-18.nii.gz
maskIsWeighted: false
numTimepts: 60
outputPath: /Users/jeff/Desktop/development/pynealOutput
pynealHost: 127.0.0.1
pynealScannerPort: 5555
resultsServerPort: 5556
