analysisChoice: Average
maskFile: /Users/jeff/gDrive/jeffCloud/real-time/pyneal/sandbox/tests/transforms/NAc_FUNC_mask.nii.gz
maskIsWeighted: false
numTimepts: 60
resultsServerPort: 5556
pynealScannerPort: 5555
