analysisChoice: Average
launchDashboard: true
maskFile: /Users/jeff/gDrive/jeffCloud/real-time/pyneal/sandbox/tests/transforms/averageFunc.nii.gz
maskIsWeighted: false
numTimepts: 60
outputPath: /Users/jeff/Desktop/development/pynealOutput
pynealScannerPort: 5555
resultsServerPort: 5556
dashboardPort: 5557
dashboardClientPort: 5558
