maskIsWeighted: False
maskFile: /Users/jeffmacinnes/gDrive/jeffCloud/real-time/pyneal/sandbox/tests/transforms/NAc_FUNC_mask.nii.gz
numTimepts: 60
outputPort: 5556
scannerPort: 5555
analysisChoice: Average
