analysisChoice: Average
maskFile: /Users/jeff/gDrive/jeffCloud/real-time/pyneal/sandbox/tests/transforms/averageFunc.nii.gz
maskIsWeighted: false
numTimepts: 60
pynealScannerPort: 5555
resultsServerPort: 5556
