maskBinarizeChoice: true
maskFile: /Users/jeffmacinnes/gDrive/jeffCloud/real-time/pyneal/sandbox/testMask.nii.gz
numTimepts: 5
outputPort: 5556
scannerPort: 5555
statsChoice: /Users/jeff/gDrive/jeffCloud/real-time/pyneal/pyneal.py
